default_language_version:
  python: python3

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: check-json
    -   id: debug-statements
    -   id: end-of-file-fixer
-   repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.971
  hooks:
  - id: mypy
    exclude: ^docs/
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
        args:
        - --profile
        - black
    -   id: isort
        name: isort (cython)
        types:
        - cython
    -   id: isort
        name: isort (pyi)
        types:
        - pyi
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.38.0
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
    -   id: pydocstyle
        additional_dependencies:
        - toml
        files: ^src/spgrep_modulation/
