default_language_version:
  python: python3

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-added-large-files
  - id: check-yaml
  - id: check-json
  - id: debug-statements
  - id: end-of-file-fixer

- repo: https://github.com/psf/black   # formatter
  rev: 22.12.0
  hooks:
  - id: black

- repo: https://github.com/astral-sh/ruff-pre-commit  # linter
  rev: v0.0.272
  hooks:
  - id: ruff
    args: [ --fix, --exit-non-zero-on-fix ]

- repo: https://github.com/pre-commit/mirrors-mypy  # type annotation
  rev: v0.991
  hooks:
  - id: mypy
    exclude: ^docs/

- repo: https://github.com/nbQA-dev/nbQA  # Notebook
  rev: 1.6.1
  hooks:
  - id: nbqa-black
